SECTION DATA
DOIS: CONST 2
OLD_DATA: SPACE
NEW_DATA: SPACE
TMP_DATA: SPACE
SECTION TEXT
COPY OLD_DATA,NEWDATA
INPUT OLD_DAT
LOAD OLD_DATA
L1: DIV DOIS
STORE  NEW_DATA
MUL DOIS
STORE TMP_DATA
LOAD OLD_DATA
SUB TMP_DATA
STORE TMP_DATA
OUTPUT TMP_DATA
LOAD OLD_DATA
JMPP L1
STOP