SECTION DATA
DOIS: CONST 2
OLD_DATA: SPACE
NEW_DATA: SPACE
TMP_DATA: SPACE
TMP_DATA: SPACE
TMP_DATA2: SPACEE
TMP_DATA3: SPACE 3
SECTION TEXT
SECTIO
COPY OLD_DATA,NEWDATA
COPY
COPY OLD_DATA,NEWDATA,ABC
INPUT L1
LOAD OLD_DATA
L1: DIV DOIS
L1: mult dois
STORE  NEW_DATA
MUL DOIS
STORE TMP_DATA
LOAD OLD_DATA
SUB TMP_DATA
STORE TMP_DATA
OUTPUT TMP_DATA
LOAD OLD_DATA
JMPP L1
STOP